use [back of house]
--
insert into canales(canal) values ('tienda')
insert into canales(canal) values ('online')
--
insert into mediosDePago(mpago) values('efectivo')
insert into mediosDePago(mpago) values('debito')
insert into mediosDePago(mpago) values('credito')
--
insert into pos(pos) values('1')
insert into pos(pos) values('2')
insert into pos(pos) values('3')
insert into pos(pos) values('4')
--
insert into turnos(turno) values('am')
insert into turnos(turno) values('pm')
--
insert into colores(color) values('blanco')
insert into colores(color) values('negro')
insert into colores(color) values('gris')
insert into colores(color) values('rosa')
insert into colores(color) values('rojo')
insert into colores(color) values('lila')
insert into colores(color) values('amarillo')
insert into colores(color) values('verde')
insert into colores(color) values('azul')
insert into colores(color) values('violeta')
insert into colores(color) values('marron')
insert into colores(color) values('naranja')
insert into colores(color) values('turquesa')
insert into colores(color) values('celeste')
--
insert into talles(talle) values('xs')
insert into talles(talle) values('s')
insert into talles(talle) values('m')
insert into talles(talle) values('l')
insert into talles(talle) values('xl')
insert into talles(talle) values('xxl')
--
insert into generos(genero) values('hombre')
insert into generos(genero) values('mujer')
insert into generos(genero) values('unisex')
--
insert into proveedores(cuit, razonSocial, telefono, direccion, mail) values('20401334932', 'delta s.a.', '1549329485', 'los talares 129', 'delta.sa@gmail.com')
insert into proveedores(cuit, razonSocial, telefono, direccion, mail) values('20292134819', 'rivera s.r.l.', '1583203755', 'riobamba 555', 'contacto@rivera.com')
insert into proveedores(cuit, razonSocial, telefono, direccion, mail) values('20381209331', 'anthares s.a.', '1529462038', 'valencia 2002', 'anthares.contacto@gmail.com')
--
use [back of house]
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('lautaro', 'villalva','40130286', 'ljvillalva@gmail.com','1537756615', '18/1/1997', '1')
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('ayelen', 'perez', '40861673', 'ayepe@gmail.com', '1583729481', '7/10/1997', '1')
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('marcos', 'leal', '41394282', 'mleal@gmail.com', '1506963211', '9/04/1997', '1')
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('sol', 'franco', '39104837', 'franco.sol@hotmail.com', '1547592857', '10/10/1996', '2')
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('carlos', 'vives', '38120948', 'vives_carlos@gmail.com', '1559672945', '3/02/1995', '2')
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('camila', 'rodriguez', '40198573', 'cami.rod@gmail.com', '1510386902', '6/01/1997', '2')
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('micaela', 'pereyra', '40864928', 'pereyra_m@gmail.com', '1545983093', '7/11/1998', '1')
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('facundo', 'gonzalez', '40398402', 'gonzalez.facundo@gmail.com', '1550395849', '3/4/1997', '1')
insert into vendedores(nombre, apellido, dni, mail, telefono, fechaNacimiento, idTurno) values('gabriel', 'escobar', '40294857', 'ga.esc@gmail.com', '47493399', '20/7/1999', '1')
--
use [back of house]
--
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo solar', '1', '1', '100', '50', '3399', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo solar', '2', '2', '22', '50', '3399', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo solar', '3', '3', '222', '50', '3399', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera solar', '4', '4', '433', '100', '4999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera solar', '5', '5', '12', '100', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera solar', '6', '6', '123', '100', '4999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera solar', '7', '1', '5', '70', '2999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera solar', '8', '2', '234', '70', '2999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera solar', '9', '3', '55', '70', '2999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('musculosa solar', '10', '4', '122', '45', '1999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon solar', '11', '5', '555', '45', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon solar', '12', '6', '1', '45', '4999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon solar', '13', '1', '554', '45', '4999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('bermuda solar', '14', '2', '322', '25', '3999', '2')
--
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo lunar', '1', '3', '34', '25', '3399', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo lunar', '2', '4', '432', '25', '3399', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo lunar', '3', '5', '34', '25', '3399', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera lunar', '4', '6', '65', '44', '3999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera lunar', '5', '1', '76', '44', '3999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera lunar', '6', '2', '4', '44', '3999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera lunar', '7', '3', '65', '33', '2999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera lunar', '8', '4', '765', '33', '2999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('musculosa lunar', '9', '5', '76', '65', '1999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('musculosa lunar', '10', '6', '67', '65', '1999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon lunar', '11', '1', '67', '28', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon lunar', '12', '2', '10', '28', '4999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon lunar', '13', '3', '12', '28', '4999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon lunar', '14', '4', '23', '28', '4999', '2')
--
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon norte', '1', '5', '33', '120', '3999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon norte', '2', '6', '206', '120', '3999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon norte', '4', '1', '77', '120', '3999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo norte', '5', '2', '120', '22', '3399', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo norte', '6', '3', '25', '22', '3399', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera norte', '7', '4', '40', '77', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera norte', '8', '5', '125', '77', '4999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera norte', '9', '6', '119', '69', '1999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('musculosa norte', '10', '1', '10', '69', '1799', '1')
--
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo sur', '11', '2', '89', '35', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo sur', '12', '3', '134', '35', '4999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo sur', '13', '4', '57', '35', '4999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo sur', '14', '5', '119', '35', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera sur', '1', '6', '22', '44', '5999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera sur', '2', '1', '120', '56', '1999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('musculosa sur', '3', '2', '43', '67', '2999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('musculosa sur', '4', '3', '30', '67', '2999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon sur', '5', '4', '24', '75', '3399', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon sur', '6', '5', '150', '75', '3399', '2')
--
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo amanecer', '7', '6', '200', '66', '4999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo amanecer', '8', '1', '120', '66', '4999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo amanecer', '9', '2', '129', '66', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo amanecer', '10', '3', '119', '66', '4999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo amanecer', '11', '4', '22', '66', '4999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo amanecer', '12', '5', '122', '66', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera amanecer', '13', '6', '127', '125', '3399', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera amanecer', '14', '1', '35', '125', '3399', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera amanecer', '1', '2', '210', '125', '3399', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera amanecer', '2', '3', '19', '20', '3999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('musculosa amanecer', '3', '4', '20', '45', '1999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('musculosa amanecer', '4', '5', '222', '45', '1999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon amanecer', '5', '6', '123', '66', '2999', '3')
--
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo atardecer', '6', '1', '119', '50', '3999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo atardecer', '7', '2', '100', '50', '3999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo atardecer', '8', '3', '198', '50', '3999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('buzo atardecer', '9', '4', '34', '50', '3999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera atardecer', '10', '5', '119', '65', '3399', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera atardecer', '11', '6', '200', '65', '3399', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('campera atardecer', '12', '1', '13', '65', '3399', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera atardecer', '13', '2', '30', '69', '2999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera atardecer', '14', '3', '15', '69', '2999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('remera atardecer', '1', '4', '40', '69', '2999', '1')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('pantalon atardecer', '2', '5', '35', '30', '4999', '2')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('bermuda atardecer', '3', '6', '119', '70', '3999', '3')
insert into productos(descripcion, idColor, idTalle, stock, stockMin, precio, idGenero) values('bermuda atardecer', '4', '1', '125', '70', '3999', '1')
--