USE [BACK OF HOUSE]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[CANALES](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[CANAL] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CANAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[COLORES](
	[ID] [int] IDENTITY(100,10) NOT NULL,
	[COLOR] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[COLOR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GENEROS](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[GENERO] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[GENERO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GRILLA](
	[UPC] [bigint] NOT NULL,
	[CONTENEDOR] [int] NOT NULL,
	[ESTANTE] [char](1) NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MEDIO_DE_PAGO](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[PAGO] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[PAGO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PEDIDOS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUIT_PROVEEDOR] [varchar](50) NOT NULL,
	[UPC] [bigint] NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[ID_COLOR] [int] NOT NULL,
	[ID_GENERO] [tinyint] NOT NULL,
	[CANTIDAD] [int] NOT NULL,
	[FECHA_INICIO] [date] NOT NULL,
	[FECHA_ENTREGA] [date] NULL,
	[ENTREGADO] [bit] NULL,
	[STOCK_MIN] [int] NULL,
	[ID_TALLE] [tinyint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[POS](
	[POS] [int] IDENTITY(100,3) NOT NULL,
	[CAJA] [tinyint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[POS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[CAJA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTOS](
	[UPC] [bigint] IDENTITY(1000,100) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[ID_COLOR] [int] NOT NULL,
	[ID_TALLE] [tinyint] NOT NULL,
	[STOCK] [int] NOT NULL,
	[STOCK_MIN] [int] NULL,
	[PRECIO] [money] NOT NULL,
	[ID_GENERO] [tinyint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[UPC] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTOS_X_VENTA](
	[ID_VENTA] [bigint] NOT NULL,
	[UPC] [bigint] NOT NULL,
	[CANTIDAD] [tinyint] NOT NULL,
	[PRECIO_UNITARIO] [money] NOT NULL
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PROVEEDORES](
	[CUIT] [varchar](50) NOT NULL,
	[RAZON_SOCIAL] [varchar](50) NULL,
	[MAIL] [varchar](50) NOT NULL,
	[TELEFONO] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[CUIT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[RAZON_SOCIAL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TALLES](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[TALLE] [varchar](30) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TALLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TURNOS](
	[ID] [tinyint] IDENTITY(1,1) NOT NULL,
	[TURNO] [varchar](2) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
UNIQUE NONCLUSTERED 
(
	[TURNO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENDEDORES](
	[LEGAJO] [int] IDENTITY(1,1) NOT NULL,
	[NOMBRE] [varchar](50) NOT NULL,
	[APELLIDO] [varchar](50) NOT NULL,
	[DNI] [varchar](11) NOT NULL,
	[MAIL] [varchar](50) NOT NULL,
	[TELEFONO] [varchar](30) NOT NULL,
	[FECHA_NAC] [date] NOT NULL,
	[ID_TURNO] [tinyint] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[LEGAJO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[VENTAS](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[ID_CANAL] [tinyint] NOT NULL,
	[ID_MEDIODEPAGOS] [tinyint] NOT NULL,
	[FECHA] [date] NOT NULL,
	[MONTO_TOTAL] [money] NOT NULL,
	[POS] [int] NOT NULL,
	[LEGAJO_VENDEDOR] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[GRILLA]  WITH CHECK ADD FOREIGN KEY([UPC])
REFERENCES [dbo].[PRODUCTOS] ([UPC])
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD FOREIGN KEY([CUIT_PROVEEDOR])
REFERENCES [dbo].[PROVEEDORES] ([CUIT])
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD FOREIGN KEY([ID_COLOR])
REFERENCES [dbo].[COLORES] ([ID])
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD FOREIGN KEY([ID_GENERO])
REFERENCES [dbo].[GENEROS] ([ID])
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD FOREIGN KEY([ID_TALLE])
REFERENCES [dbo].[TALLES] ([ID])
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD FOREIGN KEY([UPC])
REFERENCES [dbo].[PRODUCTOS] ([UPC])
GO
ALTER TABLE [dbo].[PRODUCTOS]  WITH CHECK ADD FOREIGN KEY([ID_COLOR])
REFERENCES [dbo].[COLORES] ([ID])
GO
ALTER TABLE [dbo].[PRODUCTOS]  WITH CHECK ADD FOREIGN KEY([ID_GENERO])
REFERENCES [dbo].[GENEROS] ([ID])
GO
ALTER TABLE [dbo].[PRODUCTOS]  WITH CHECK ADD FOREIGN KEY([ID_TALLE])
REFERENCES [dbo].[TALLES] ([ID])
GO
ALTER TABLE [dbo].[PRODUCTOS_X_VENTA]  WITH CHECK ADD FOREIGN KEY([ID_VENTA])
REFERENCES [dbo].[VENTAS] ([ID])
GO
ALTER TABLE [dbo].[PRODUCTOS_X_VENTA]  WITH CHECK ADD FOREIGN KEY([UPC])
REFERENCES [dbo].[PRODUCTOS] ([UPC])
GO
ALTER TABLE [dbo].[VENDEDORES]  WITH CHECK ADD FOREIGN KEY([ID_TURNO])
REFERENCES [dbo].[TURNOS] ([ID])
GO
ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD FOREIGN KEY([ID_CANAL])
REFERENCES [dbo].[CANALES] ([ID])
GO
ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD FOREIGN KEY([ID_MEDIODEPAGOS])
REFERENCES [dbo].[MEDIO_DE_PAGO] ([ID])
GO
ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD FOREIGN KEY([LEGAJO_VENDEDOR])
REFERENCES [dbo].[VENDEDORES] ([LEGAJO])
GO
ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD FOREIGN KEY([POS])
REFERENCES [dbo].[POS] ([POS])
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD CHECK  (([CANTIDAD]>(0)))
GO
ALTER TABLE [dbo].[PEDIDOS]  WITH CHECK ADD CHECK  (([STOCK_MIN]>(0)))
GO
ALTER TABLE [dbo].[PRODUCTOS]  WITH CHECK ADD CHECK  (([PRECIO]>(0)))
GO
ALTER TABLE [dbo].[PRODUCTOS]  WITH CHECK ADD CHECK  (([STOCK]>(0)))
GO
ALTER TABLE [dbo].[PRODUCTOS]  WITH CHECK ADD CHECK  (([STOCK_MIN]>(0)))
GO
ALTER TABLE [dbo].[PRODUCTOS_X_VENTA]  WITH CHECK ADD CHECK  (([CANTIDAD]>(0)))
GO
ALTER TABLE [dbo].[PRODUCTOS_X_VENTA]  WITH CHECK ADD CHECK  (([PRECIO_UNITARIO]>(0)))
GO
ALTER TABLE [dbo].[VENTAS]  WITH CHECK ADD CHECK  (([MONTO_TOTAL]>(0)))
GO
